-- FraudGuard canonical PostgreSQL schema for a clean installation.
--
-- This is a fresh-install schema, not a reconstruction of the unavailable
-- historical pre-V2 DDL. It contains no application data and no Flyway
-- history table. The explicit bootstrap procedure records Flyway baseline 3
-- after this file has been applied.

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    CONSTRAINT users_role_check CHECK (role IN ('ADMIN', 'USER'))
);

CREATE TABLE integrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    api_key_hash VARCHAR(64) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255),
    amount DOUBLE PRECISION NOT NULL,
    currency VARCHAR(255),
    recipient VARCHAR(255),
    transaction_type VARCHAR(255),
    location VARCHAR(255),
    device_id VARCHAR(255),
    is_new_recipient BOOLEAN NOT NULL,
    is_new_device BOOLEAN NOT NULL,
    recent_transaction_count INTEGER NOT NULL,
    transactions_in_time_window INTEGER NOT NULL,
    repeated_transactions_to_recipient INTEGER NOT NULL,
    risk_score INTEGER NOT NULL,
    risk_level VARCHAR(255),
    fraud_action VARCHAR(255),
    analyzed_at TIMESTAMP WITHOUT TIME ZONE,
    integration_id BIGINT,
    CONSTRAINT fk_transactions_integration
        FOREIGN KEY (integration_id) REFERENCES integrations(id)
);

CREATE INDEX idx_transactions_integration_id
    ON transactions(integration_id);

CREATE TABLE transaction_reasons (
    transaction_id BIGINT NOT NULL,
    reasons VARCHAR(255),
    CONSTRAINT fk_transaction_reasons_transaction
        FOREIGN KEY (transaction_id) REFERENCES transactions(id)
);
